/// Generated by AssetsRefGenerator on 2022/03/09
class Res {
  static const String apple = "assets/images/apple.svg";
  static const String ar = "assets/lang/ar.json";
  static const String arrow = "assets/images/arrow.svg";
  static const String en = "assets/lang/en.json";
  static const String facebook = "assets/images/facebook.svg";
  static const String icon = "assets/images/foz_logo.png";
  static const String logo = "assets/images/foz_logo.png";
  static const String logoSvg = "assets/images/logoSvg.svg";
  static const String check = "assets/images/check.svg";
  static const String marker = "assets/images/marker.png";
  static const String mobile = "assets/images/mobile.svg";
  static const String password = "assets/images/password.svg";
  static const String offline = "assets/images/offline.png";
  static const String appLoaderBg = "assets/images/appLoaderBg.png";
  static const String errorSnackBar = "assets/images/error_snack_bar.svg";
  static const String warningSnackBar = "assets/images/warning_snack_bar.svg";
  static const String successSnackBar = "assets/images/success_snack_bar.svg";
  static const String splash = 'assets/lottie/splash.json';
  static const String timerImage = 'assets/lottie/timer_image.json';
  static const String watch = 'assets/lottie/watch.json';
  static const String payCouponAnim = 'assets/lottie/pay_coupon_anim.json';
  static const String success = 'assets/lottie/success.json';

  static const String noInternet = 'assets/lottie/noInternet.json';
  static const String error = 'assets/lottie/error.json';
  static const String emptyFaq = 'assets/lottie/emptyFaq.json';
  static const String auction = 'assets/lottie/auction.json';
  static const String wallet = 'assets/lottie/wallet.json';
  static const String noNotifications = 'assets/lottie/noNotifications.json';
  static const String auctionTimer = 'assets/lottie/auction_timer_loading.json';
  static const String vipIconOnName = 'assets/lottie/vip_icon_on_name.json';
  static const String raffles = 'assets/lottie/raffles.json';
  static const String goldIcon = 'assets/lottie/gold_icon.json';
  static const String onboarding1Icon = 'assets/images/onboarding_1.png';
  static const String onboarding2Icon = 'assets/images/onboarding_2.png';
  static const String onboarding3Icon = 'assets/images/onboarding_3.png';
  static const String editIcon = 'assets/images/ic_edit.svg';
  static const String wave = 'assets/images/wave.png';
  static const String editPhone = 'assets/images/edit_phone.svg';
  static const String calendarIcon = 'assets/images/calendar_icon.svg';
  static const String promocode = 'assets/images/promocode.svg';
  static const String rightIcon = 'assets/images/rightIcon.png';
  static const String selectedIcon = 'assets/images/selectedIcon.svg';
  static const String pnScreenImage = 'assets/images/pnScreenImage.png';
  static const String saudiFlag = 'assets/images/saudi-arabia_flag.svg';
  static const String walletIcon = 'assets/images/icons/wallet.png';
  static const String tagIcon = 'assets/images/icons/Tag.png';
  static const String notificationIcon = 'assets/images/icons/notification.png';
  static const String userIcon = 'assets/images/icons/user.png';
  static const String homeIcon = 'assets/images/icons/home.png';
  static const String notificationInfoIcon = 'assets/images/ic_notification_info.svg';
  static const String notificationBell = 'assets/images/not_bell.svg';
  static const String timerWatch = 'assets/images/icons/timer_watch.svg';
  static const String edit = 'assets/images/edit.png';
  static const String vipImage = 'assets/images/assets/images/vip_image.png';

  //bottom nav bar
  static const String home = 'assets/images/icons/home.svg';
  static const String auctionIcon = 'assets/images/icons/auction.svg';
  static const String walletNewIcon = 'assets/images/icons/wallet.svg';
  static const String walletHomeIcon = 'assets/images/icons/wallet_home_icon.svg';
  static const String shop = 'assets/images/icons/shop.svg';
  static const String more = 'assets/images/icons/more.svg';

  //wallet
  static const String profileIcon = 'assets/images/icons/profile_icon.svg';
  static const String helpIcon = 'assets/images/icons/help_icon.svg';
  static const String priceIcon = 'assets/images/icons/price_icon.svg';
  static const String warningIcon = 'assets/images/icons/warning_icon.svg';
  static const String addWallet = 'assets/images/icons/add_wallet.svg';
  static const String previousOperations = 'assets/images/icons/previous_operations.svg';
  static const String withdraw = 'assets/images/icons/withdraw.svg';
  static const String appleIcon = 'assets/images/icons/apple.svg';
  static const String mada = 'assets/images/icons/mada.svg';
  static const String visa = 'assets/images/icons/visa.svg';
  static const String masterCard = 'assets/images/icons/mastercard.png';
  static const String card = 'assets/images/icons/card.svg';
  static const String document = 'assets/images/icons/document.svg';
  static const String questionMark = 'assets/images/icons/questionMark.svg';
  static const String cardTypes = 'assets/images/card_types.png';

  //previous operations
  static const String operationsDateIcon = 'assets/images/icons/operations_date_icon.svg';
  static const String arrowBack = 'assets/images/icons/arrow_back.svg';
  static const String charging = 'assets/images/icons/charging.svg';
  static const String closeIcon = 'assets/images/icons/close_icon.svg';
  static const String chargeFailed = 'assets/images/charge_failed.png';
  static const String chargeSuccess = 'assets/images/charge_success.png';

  //profile
  static const String addIcon = 'assets/images/icons/add_icon.svg';
  static const String logout = 'assets/images/icons/logout_icon.svg';
  static const String login = 'assets/images/icons/login_icon.svg';
  static const String vipIcon = 'assets/images/icons/vip_icon.svg';
  static const String defaultImage = 'assets/images/icons/default_image.svg';
  static const String inviteFriend = 'assets/images/icons/invite_friend.svg';
  static const String personalProfile = 'assets/images/icons/personal_profile.svg';
  static const String chat = 'assets/images/icons/chat.svg';
  static const String stars = 'assets/images/icons/stars.svg';
  static const String paymentPolicy = 'assets/images/icons/payment_policy.svg';
  static const String sendPoints = 'assets/images/icons/send_points.svg';
  static const String transferPoints = 'assets/images/icons/transfer_points.svg';
  static const String equal = 'assets/images/icons/equal.svg';
  static const String xApp = 'assets/images/icons/x_app.svg';
  static const String snap = 'assets/images/icons/snap.svg';
  static const String loyaltyProgram = 'assets/images/icons/loyalty_program.svg';
  static const String editProfile = 'assets/images/icons/edit_profile.svg';
  static const String instagram = 'assets/images/icons/instagram.svg';
  static const String fozPartner = 'assets/images/icons/foz_partner.svg';
  static const String done = 'assets/images/icons/done.svg';
  static const String share = 'assets/images/icons/share.svg';
  static const String friendInvitation = 'assets/images/icons/friend_invitation.svg';
  static const String completeInvitations = 'assets/images/icons/complete_invitations.svg';
  static const String galleryEdit = 'assets/images/icons/gallery_edit.svg';
  static const String deleteAccount = 'assets/images/icons/delete_account.svg';
  static const String masterIcon = 'assets/images/ic_visa.svg';
  static const String applePayIcon = 'assets/images/apple-pay.png';

  //home
  static const String fozBG = 'assets/images/foz_bg.png';
  static const String vipFozBG = 'assets/images/vipFozBg.png';
  static const String offerBG = 'assets/images/offer_bg.png';
  static const String sortIcon = 'assets/images/icons/sort_icon.svg';
  static const String starsImage = 'assets/images/stars.svg';
  static const String auctionTermsIcon = 'assets/images/icons/auction_terms_icon.svg';
  static const String sellCoupon = 'assets/images/icons/sell_coupon.svg';
  static const String viewIcon = 'assets/images/icons/view_icon.svg';
  static const String leaveAuctionIcon = 'assets/images/icons/leave_auction_icon.svg';
  static const String finishAuctionStars = 'assets/images/icons/finish_auction_stars.svg';
  static const String favIcon = 'assets/images/icons/fav_icon.svg';
  static const String deleteAcc = 'assets/images/icons/delete_acc.svg';
  static const String codeBg = 'assets/images/icons/code_bg.png';
  static const String fullNameIcon = 'assets/images/icons/full_name_icon.svg';
}
